export default {
  appName: 'First Project',
  login: 'Login',
  welcome: 'Welcome',
  username: 'Username',
  password: 'Password',
  loginButton: 'Login',
  errorLogin: 'Login failed. Please try again.',
  welcomeMessage: 'Welcome, ',
  backToLogin: 'Back to Login',
  
  // Forgot password strings
  forgotPassword: 'Forgot Password',
  email: 'Email',
  sendOTP: 'Send OTP',
  resetPassword: 'Reset Password',
  enterOTP: 'Enter OTP',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  resetPasswordButton: 'Reset Password',
  forgotPasswordLink: 'Forgot Password?',
  otpSent: 'OTP sent to your email',
  errorSendingOTP: 'Failed to send OTP. Please try again.',
  passwordsDoNotMatch: 'Passwords do not match',
  passwordResetSuccess: 'Password reset successful',
  errorResetPassword: 'Failed to reset password. Please try again.',
  
  // Sign up strings
  signup: 'Sign Up',
  signupButton: 'Sign Up',
  alreadyHaveAccount: 'Already have an account? Login',
  noAccount: 'Don\'t have an account? Sign up',
  signupSuccess: 'Registration successful! Please login.',
  
  // Dashboard strings
  dashboard: 'Dashboard',
  storeActivity: 'Store Activity',
  paidVisibilityTracker: 'Paid Visibility Tracker',
  captureEvidence: 'Capture Evidence',
  logout: 'Logout',
  elementName: 'Element Name:',
  subTypeName: 'Sub Type Name:',
  execution: 'Execution:',
  planName: 'Plan Name:',
  brandName: 'Brand Name:',
  planEndDate: 'End:',
  previous: 'Previous',
  next: 'Next',
  page: 'Page',
  of: 'of',
  noDataAvailable: 'No data available',
  
  // Evidence Capture Flow
  performActivity: 'Perform Activity',
  fillForm: 'Fill Form',
  evidenceTags: 'Evidence Tags',
  isValidEvidenceAvailable: 'Is Valid Evidence Available?',
  yes: 'Yes',
  no: 'No',
  takePhoto: 'Take Photo',
  chooseFromGallery: 'Choose from Gallery',
  reason: 'Reason',
  submit: 'Submit',
  cancel: 'Cancel',
  evidenceSubmitted: 'Evidence submitted successfully!',
  reasonOptions: [
    'Element Fixture Not Ready',
    'Product Missing',
    'Store Closed',
    'No Access to Store',
    'Other'
  ],
  
  // Other strings
  passwordResetSuccess: 'Password reset successful',
  passwordsDoNotMatch: 'Passwords do not match',
  otpSent: 'OTP sent to your email',
  backToLogin: 'Back to Login',
  errorSendingOTP: 'Failed to send OTP. Please try again.',
  errorResetPassword: 'Failed to reset password. Please check your OTP and try again.'
};
